name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
  
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Tailwind CLI
        run: |
          curl -o tailwindcss -L https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss
          
      - name: Generate
        run: ./tailwindcss -i input.css -o dist/main.css
        
      - name: Miscellaneous
        run: |
          rm tailwindcss
          echo `date +%s` > last-updated.txt
        
      - name: Push to GitHub 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update ($(date +'%Y-%m-%dT%H:%M:%S'))"
          git push