name: Build

on:
  push:
    branches: ["main"]
  
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Tailwind CLI
        run: |
          curl -o tailwindcss -L https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss
      - name: Generate Main
        run: |
          ./tailwindcss -i input.css -o dist/main.css
          ./tailwindcss -i input.css -o dist/main.min.css --minify
      - name: Generate Variants
        run: |
          ./tailwindcss -i input.css -o dist/variants/dark.css -c variants/dark.config.js
          ./tailwindcss -i input.css -o dist/variants/dark.min.css -c variants/dark.config.js --minify
          ./tailwindcss -i input.css -o dist/variants/hover.css -c variants/hover.config.js
          ./tailwindcss -i input.css -o dist/variants/hover.min.css -c variants/hover.config.js --minify
          ./tailwindcss -i input.css -o dist/variants/lg.css -c variants/lg.config.js
          ./tailwindcss -i input.css -o dist/variants/lg.min.css -c variants/lg.config.js --minify
          ./tailwindcss -i input.css -o dist/variants/md.css -c variants/md.config.js
          ./tailwindcss -i input.css -o dist/variants/md.min.css -c variants/md.config.js --minify
          ./tailwindcss -i input.css -o dist/variants/xl.css -c variants/xl.config.js
          ./tailwindcss -i input.css -o dist/variants/xl.min.css -c variants/xl.config.js --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
